### ISSUE TITLE
Does not match expected packet size

### ISSUE THREAD

**Issue by keke1229488344** [Tiiffi/mcrcon#25] opened 2019-05-25 04:43 UTC
Sometimes when I type the help command（ ./mcrcon -p "password" -H IP -P Port "help"）, it returns "Warning: recv() return value (1408) does not match expected packet size (3133)."

**Comment by IIPoliII** [comment] 2019-07-25 13:45
Same for me i have no idea what is due too

**Comment by IIPoliII** [comment] 2019-07-26 13:17
The fix was easy simply fork it and do this https://github.com/joinandplaycoop/mcrcon/commit/30c39b7ddfe526621d60b30644d6d84df0180e35

**Comment by Tiiffi** [comment] 2019-09-20 09:24
> Sometimes when I type the help command（ ./mcrcon -p "password" -H IP -P Port "help"）, it returns "Warning: recv() return value (1408) does not match expected packet size (3133)."

What Minecraft server version you are using?

**Comment by joshuasuperboy** [comment] 2019-10-08 19:05
If your not port forwarding a specific port you set in the server.properties file for the RCON in the server folder then the RCON will not work. I had the same problem when trying to connect to port 25560 but when i tried to connect to my server port which was 25565 that port was being port forwarded it said what it told you what you will have to do is specify something other then port 25565 in the server.properties file in the server folder for the RCON port and then you will have to change the enabled rcon to true then specify a password which i would reccomend doing and when your typing in the ip make sure its your public ip and not your private ip address then it should work fine

**Comment by northkillz** [comment] 2019-10-17 03:01
I'm having this issue too.

I tried both `mcrcon` and `rconc` and both produced the same error complaining insufficient read byte numbers. And the error occurs inconsistently, i.e. command sometimes succeeds.

I'm using Spigot server for Minecraft version 1.14.4

**Comment by northkillz** [comment] 2019-10-17 07:04
I think [this SO post](https://stackoverflow.com/a/4509605/5406471) explains it.

In some situation data transmission may be fragmented and `recv` should handle this case but `mcrcon` does not.

**Comment by Tiiffi** [comment] 2019-10-17 15:37
@northkillz thank you!

This internet protocol and recv() fragmentation behaviour is definately something I had overlooked and I will probably merge your pull request after some testing.

But there is something that bothers me. According to my tests `/help` command shouldn't even produce packets bigger than `~500` bytes.

Original issue description mentions expected packet size of `3133` which suggests that the server is trying to send more data than I would ever expect from `/help` command response.

First I was thinking it might be trying to send multi-packet responses (it's in Source RCON spec but wasn't supported by Minecraft at the time mcrcon was written) but maximun allowed single packet size is `4096` so it doesn't make sense to split the packet if the response size is only 3133 bytes.

For now I cannot reproduce the problem on my local network (with Vanilla 1.14.4 or Spigot 1.14.4) so it's still kinda mystery what exactly is going on.

**I would be grateful if someone could provide pcap packet capture when this problem happens.**
_!!! Be careful not to include password in the capture !!!_

**Comment by northkillz** [comment] 2019-10-21 02:11
When I issue `help`, server returns
```
/advancement (grant|revoke)
/ban <targets> [<reason>]
/ban-ip <target> [<reason>]
/banlist [ips|players]
/bossbar (add|get|list|remove|set)
/clear [<targets>]
/clone <begin> <end> <destination> [filtered|masked|replace]
/data (get|merge|modify|remove)
/datapack (disable|enable|list)
/debug (report|start|stop)
/defaultgamemode (adventure|creative|spectator|survival)
/deop <targets>
/difficulty [easy|hard|normal|peaceful]
/effect (clear|give)
/enchant <targets> <enchantment> [<level>]
/execute (align|anchored|as|at|facing|if|in|positioned|rotated|run|store|unless)
/experience (add|query|set)
/fill <from> <to> <block> [destroy|hollow|keep|outline|replace]
/forceload (add|query|remove)
/function <name>
/gamemode (adventure|creative|spectator|survival)
/gamerule (announceAdvancements|commandBlockOutput|disableElytraMovementCheck|disableRaids|doDaylightCycle|doEntityDrops|doFireTick|doLimitedCrafting|doMobLoot|doMobSpawning|doTileDrops|doWeatherCycle|keepInventory|logAdminCommands|maxCommandChainLength|maxEntityCramming|mobGriefing|naturalRegeneration|randomTickSpeed|reducedDebugInfo|sendCommandFeedback|showDeathMessages|spawnRadius|spectatorsGenerateChunks)
/give <targets> <item> [<count>]
/help [<command>]
/kick <targets> [<reason>]
/kill <targets>
/list [uuids]
/locate (Buried_Treasure|Desert_Pyramid|EndCity|Fortress|Igloo|Jungle_Pyramid|Mansion|Mineshaft|Monument|Ocean_Ruin|Pillager_Outpost|Shipwreck|Stronghold|Swamp_Hut|Village)
/loot (give|insert|replace|spawn)
/me <action>
/msg <targets> <message>
/op <targets>
/pardon <targets>
/pardon-ip <target>
/particle <name> [<pos>]
/playsound <sound> (ambient|block|hostile|master|music|neutral|player|record|voice|weather)
/recipe (give|take)
/reload
/replaceitem (block|entity)
/save-all [flush]
/save-off
/save-on
/say <message>
/schedule function <function> <time>
/scoreboard (objectives|players)
/seed
/setblock <pos> <block> [destroy|keep|replace]
/setidletimeout <minutes>
/setworldspawn [<pos>]
/spawnpoint [<targets>]
/spreadplayers <center> <spreadDistance> <maxRange> <respectTeams> <targets>
/stop
/stopsound <targets> [*|ambient|block|hostile|master|music|neutral|player|record|voice|weather]
/summon <entity> [<pos>]
/tag <targets> (add|list|remove)
/team (add|empty|join|leave|list|modify|remove)
/teammsg <message>
/teleport (<destination>|<location>|<targets>)
/tell -> msg
/tellraw <targets> <message>
/time (add|query|set)
/title <targets> (actionbar|clear|reset|subtitle|times|title)
/tm -> teammsg
/tp -> teleport
/trigger <objective> [add|set]
/w -> msg
/weather (clear|rain|thunder)
/whitelist (add|list|off|on|reload|remove)
/worldborder (add|center|damage|get|set|warning)
/xp -> experience
```
(I inserted new lines for readability)
I don't have any knowledge of RCON protocol, but if it's sent as ascii, that would be 2616 bytes (+ 10 bytes of header). I can't provide packet captures, because I'm using private tunnel to access the server, so packets are encrypted.

Anyway the only RCON protocol spec. I could find is [Valve's Source RCON protocol](https://developer.valvesoftware.com/wiki/Source_RCON_Protocol), There's guarantee that data greater than maximum possible size (4096) will be split. But it does not mention the other case. So I think the behavior of sending data lesser than 4096 bytes is implement specific.

**Comment by Tiiffi** [comment] 2019-10-21 10:13
Thank you.

That output listing was helpful. Looks like new server versions are pushing the help listing without pagination which explains the bigger packet sizes and makes the fragmentation problem more likely.

So basically they changed the behaviour a bit. Too bad they still didn't fix missing newlines in vanilla server.

Anyway, I merged your patch and it should be fine for now.

**Closed by Tiiffi** 2019-10-21 10:13 UTC
Labels: Help wanted, bug
