### ISSUE TITLE
Error 111

### ISSUE THREAD

**Issue by garteth** [Tiiffi/mcrcon#46] opened 2020-04-05 10:44 UTC
I have followed an installation via the linuxize dot com website.

At the stage of connection to the console everything was working fine. I then rebooted my VM and now I get the message

Connection Failed
Error 111: Connection refused

Any ideas?

**Comment by Toxicterror** [comment] 2020-07-01 18:54
same here, also looking for a solution

**Comment by Tiiffi** [comment] 2020-09-01 23:49
Duplicate of https://github.com/Tiiffi/mcrcon/issues/55

**Closed by Tiiffi** 2020-09-01 23:49 UTC
Labels: duplicate
